dataset_choice = ['coco_text', 'receipt', 'synthtext']
IMAGE_SIZE = 608
BATCH_SIZE = 2
BUFFER_SIZE = 300
NUM_CLASS = 2
PREFETCH_SIZE = 5
LR_INIT = 1e-3
LR_END = 1e-6
WARMUP_EPOCHS = 1
TRAIN_EPOCHS = 5
yolo_iou_threshold = 0.5
yolo_score_threshold = 0.5
